### PR TITLE
PBI-36: delete assignment

### LINKED ISSUE #75: PBI-36: Teacher can delete assignment in class
**Story Points: 8**

### PR DESCRIPTION
**Pull request by AldiNFitrah**

### CODE REVIEW

**Review by nofamex — COMMENTED** [review]
LGTM

**Review by nofamex — APPROVED** [review]
LGTM, Merge now cause i need this

**Review by fxdros — APPROVED** [review]
LGTM, thanks for your hard work!

**Review by Zsaschz — APPROVED** [review]
Super clean commit, nice work!

**Review by kanziebub — APPROVED** [review]
LGTM great job uwu

**Pull request merged**
